import dotenv from "dotenv";
import mongoose from "mongoose";
import { connectDB } from "../config/database";
import { Product } from "../models/Product";

dotenv.config();

const products = [
  { name: "Bamboo Toothbrush Set (4-Pack)", description: "Biodegradable bamboo handles with BPA-free bristles and compostable packaging.", longDescription: "Each handle is carved from a single piece of Moso bamboo, a fast-regenerating grass that reaches harvest maturity in 3–5 years versus decades for hardwood. The bristles are made from a BPA-free nylon blend designed to break down faster than standard plastic bristles, and the whole set ships in a compostable cardboard sleeve with zero plastic wrap. Each handle is stamped with a use-by guide so the whole household can track replacement cycles together.", price: 12.99, category: "home", ecoScore: 88, images: ["https://images.unsplash.com/photo-1607613009820-a29f7bb81c04", "https://images.unsplash.com/photo-1564507004663-b6dfb3c824d5", "https://images.unsplash.com/photo-1602910344008-22f323cc1817"], rating: 4.6, ratingCount: 214, stock: 120 },
  { name: "Reusable Silicone Food Bags (6-Pack)", description: "Leak-proof, dishwasher-safe silicone storage replacing single-use plastic bags.", longDescription: "Made from food-grade platinum silicone rated for -40°F to 450°F, these bags handle freezer storage, microwave reheating, and even sous-vide cooking without leaching. The self-sealing zip track is tested for 3,000+ open-close cycles, and the set includes three sizes (8oz, 16oz, 32oz) to cover snacks through meal prep. Each bag replaces roughly 200–300 disposable bags over its working life.", price: 24.5, category: "home", ecoScore: 82, images: ["https://images.unsplash.com/photo-1610348725531-816f4626ec18", "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7", "https://images.unsplash.com/photo-1611171711912-9a9c6d8d9c98"], rating: 4.4, ratingCount: 158, stock: 90 },
  { name: "Solar-Powered Phone Charger", description: "10,000mAh power bank with an integrated solar panel for off-grid charging.", longDescription: "A monocrystalline solar panel (the most efficient commercially available cell type) tops up the internal 10,000mAh lithium battery during daylight, while dual USB-A and USB-C outputs let you charge two devices at once. The IP65-rated shell handles rain and dust, making it suitable for hiking, camping, or emergency backup power. A full panel charge from empty takes roughly 20 hours of direct sun, or 4 hours via wall adapter.", price: 39.99, category: "home", ecoScore: 75, images: ["https://images.unsplash.com/photo-1620714223084-86bff43c7e58", "https://images.unsplash.com/photo-1592833159155-92a0904a8e0e", "https://images.unsplash.com/photo-1518770660439-4636190af475"], rating: 4.2, ratingCount: 97, stock: 60 },
  { name: "Organic Cotton Bedsheet Set", description: "GOTS-certified organic cotton, undyed and chemical-free finishing.", longDescription: "Grown without synthetic pesticides or fertilizers and certified end-to-end under the Global Organic Textile Standard, this 300-thread-count set skips chlorine bleaching and synthetic dyes entirely, relying on the cotton's natural cream tone. The weave is breathable enough for warm climates while still holding up to regular washing without pilling. Includes a fitted sheet, flat sheet, and two pillowcases.", price: 89.0, category: "home", ecoScore: 91, images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af", "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85", "https://images.unsplash.com/photo-1631049307264-da0ec9d70304"], rating: 4.8, ratingCount: 132, stock: 45 },
  { name: "Recycled Denim Jacket", description: "Made from 80% post-consumer recycled denim fiber, classic unisex fit.", longDescription: "Post-consumer denim is shredded, re-spun, and blended with 20% organic cotton for structural strength, cutting water use dramatically versus virgin denim production (which can run 1,800+ gallons per pair of jeans). Each jacket carries a small fabric tag noting the approximate recycled-fiber percentage by weight. The cut is a relaxed unisex fit that sizes true to standard denim charts.", price: 68.0, category: "fashion", ecoScore: 79, images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5", "https://images.unsplash.com/photo-1543087903-1ac2ec7aa8c5", "https://images.unsplash.com/photo-1525450824786-227cbef70703"], rating: 4.3, ratingCount: 76, stock: 35 },
  { name: "Hemp Canvas Tote Bag", description: "Durable hemp-cotton canvas built to replace hundreds of plastic bags over its lifetime.", longDescription: "Hemp fiber requires roughly half the water of cotton to grow and naturally resists mold and UV degradation, making this canvas suited to years of daily use. Reinforced stitching at the strap base prevents the most common tote failure point, and the bag is rated to carry up to 40lbs. One tote used for two years offsets the production footprint of an estimated 500+ single-use plastic bags.", price: 22.0, category: "fashion", ecoScore: 85, images: ["https://images.unsplash.com/photo-1591561954557-26941169b49e", "https://images.unsplash.com/photo-1597481499750-3e6b22637e12", "https://images.unsplash.com/photo-1544816155-12df9643f363"], rating: 4.7, ratingCount: 203, stock: 150 },
  { name: "Cork Leather Wallet", description: "Vegan leather alternative made from sustainably harvested cork bark.", longDescription: "Cork is harvested from the bark of cork oak trees without felling them — the bark regenerates over roughly 9 years, making it one of the few truly renewable leather alternatives. The material is naturally water-resistant and develops a soft patina with use, similar to genuine leather. Internal card slots are reinforced with a thin fabric backing to prevent stretching over time.", price: 34.0, category: "fashion", ecoScore: 87, images: ["https://images.unsplash.com/photo-1627123424574-724758594e93", "https://images.unsplash.com/photo-1627123042770-bf3d24e35e95", "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d"], rating: 4.5, ratingCount: 64, stock: 70 },
  { name: "Recycled Wool Sweater", description: "Knit from 70% reclaimed wool fiber in undyed natural tones.", longDescription: "Reclaimed wool is sourced from post-industrial textile waste, mechanically shredded, and re-spun rather than relying on virgin sheep wool — cutting both water use and land impact significantly. The remaining 30% is a long-staple cotton blended in for softness and shape retention. Colors are left undyed and sorted by the natural shade of the source wool, so each batch has subtle tonal variation.", price: 72.0, category: "fashion", ecoScore: 81, images: ["https://images.unsplash.com/photo-1576871337622-98d48d1cf531", "https://images.unsplash.com/photo-1610652492500-ded49ceeb378", "https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4"], rating: 4.4, ratingCount: 58, stock: 40 },
  { name: "Compostable Coffee Pods (24-Pack)", description: "Fully compostable pods compatible with standard single-serve machines.", longDescription: "The pod shell is made from a corn-starch-based bioplastic certified for home composting, breaking down within 90–180 days in active compost conditions (not in landfill, where oxygen is limited). Coffee inside is sourced from Rainforest Alliance certified farms. Compatible with standard single-serve brewing systems without an adapter.", price: 14.99, category: "food", ecoScore: 78, images: ["https://images.unsplash.com/photo-1497935586351-b67a49e012bf", "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085", "https://images.unsplash.com/photo-1442550528053-c431ecb55509"], rating: 4.1, ratingCount: 189, stock: 200 },
  { name: "Reusable Beeswax Food Wraps", description: "Organic cotton infused with beeswax — a direct replacement for plastic cling wrap.", longDescription: "Organic cotton is hand-coated with a blend of beeswax, tree resin, and jojoba oil, which together create a tacky, moldable seal when warmed slightly between your hands. The wax layer naturally resists bacteria growth, and a single wrap typically lasts 6–12 months of regular use before needing a refresh coating. Wash in cool water only — hot water melts the wax layer.", price: 18.5, category: "food", ecoScore: 89, images: ["https://images.unsplash.com/photo-1610348725531-816f4626ec18", "https://images.unsplash.com/photo-1582735689369-4fe89db7114c", "https://images.unsplash.com/photo-1610701596007-11502861dcfa"], rating: 4.6, ratingCount: 142, stock: 110 },
  { name: "Stainless Steel Bento Box", description: "Leak-proof three-compartment lunch box made of fully recyclable stainless steel.", longDescription: "18/8 food-grade stainless steel resists staining and odor retention far better than plastic alternatives, and is fully recyclable at end of life rather than ending up as microplastic. The three-compartment layout uses a silicone gasket seal rated leak-proof for liquids, tested for daily commute conditions. Dishwasher safe, though hand-washing extends the gasket's lifespan.", price: 29.99, category: "food", ecoScore: 84, images: ["https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7", "https://images.unsplash.com/photo-1604908554007-31cb6cb14bb6", "https://images.unsplash.com/photo-1547592180-85f173990554"], rating: 4.5, ratingCount: 97, stock: 80 },
  { name: "Foldable E-Bike", description: "Lightweight aluminum-frame e-bike with 40km range, built to replace short car trips.", longDescription: "The 6061 aluminum frame folds in under 15 seconds for storage in a car trunk or apartment closet, while the 36V battery delivers up to 40km of pedal-assist range depending on terrain and rider weight. A torque sensor (rather than cheaper cadence sensors) provides smoother power delivery that feels closer to natural pedaling. Replacing a 10km round-trip car commute with this bike a few times a week adds up to meaningful annual emissions savings.", price: 899.0, category: "transport", ecoScore: 93, images: ["https://images.unsplash.com/photo-1485965120184-e220f721d03e", "https://images.unsplash.com/photo-1571333250630-f0230c320b6d", "https://images.unsplash.com/photo-1571068316344-75bc76f77890"], rating: 4.7, ratingCount: 41, stock: 12 },
  { name: "Carbon Fiber Commuter Scooter", description: "Lightweight electric scooter purpose-built for daily urban commuting.", longDescription: "A carbon-fiber-reinforced deck cuts overall weight to under 13kg while maintaining a 100kg load rating, making it easier to carry up stairs or onto transit than typical aluminum scooters. The motor is tuned for steady acceleration rather than top speed, prioritizing battery efficiency and control on shared bike lanes. IP54 water resistance handles light rain commutes.", price: 549.0, category: "transport", ecoScore: 86, images: ["https://images.unsplash.com/photo-1604868189265-219ba2705e07", "https://images.unsplash.com/photo-1604868189437-22e1ec4d3a02", "https://images.unsplash.com/photo-1599301226469-2fdcdb5d8c1d"], rating: 4.3, ratingCount: 29, stock: 18 },
  { name: "Recycled Bike Helmet", description: "Impact-tested helmet shell made from recycled ABS plastic.", longDescription: "The outer shell is injection-molded from post-industrial recycled ABS plastic, meeting the same CPSC impact standards as virgin-plastic helmets despite the recycled content. EPS foam liner absorbs impact energy on a single use basis — like all helmets, replace after any significant impact. Ventilation channels are positioned based on airflow testing rather than purely aesthetic placement.", price: 45.0, category: "transport", ecoScore: 80, images: ["https://images.unsplash.com/photo-1576435728678-68d0fbf94e91", "https://images.unsplash.com/photo-1559348349-86f1f65817fe", "https://images.unsplash.com/photo-1571333250630-f0230c320b6d"], rating: 4.4, ratingCount: 53, stock: 65 },
];

async function seed() {
  await connectDB();
  await Product.deleteMany({});
  await Product.insertMany(products);
  console.log(`✅ Seeded ${products.length} products`);
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});